### ISSUE TITLE
请问未来可以考虑加入导出收藏的功能吗？

### ISSUE THREAD

**Issue by i-iooi-i** [meterscao/Speechless#1]
微博账号被夹了，只能登录，不能点赞，不能收藏，不能关注，不能评论。哭了~ 
现在唯一割舍不下的就是收藏的内容，若是可以导出收藏，那么弃号也没所谓了。🥲

**Comment by meterscao** [comment]
我没有关注过收藏的内容，等先了解下看看有什么结论给你同步下～

**Comment by meterscao** [comment]
你的收藏主要是什么内容，视频、长文、图片？

**Comment by i-iooi-i** [comment]
> 你的收藏主要是什么内容，视频、长文、图片？

来了来了~  我想大部分人都是图片跟长文居多哈，视频几乎很少的。😊
