### ISSUE TITLE
有考虑过开发 Firefox 版吗？

### ISSUE THREAD

**Issue by Kaangnakamuyi** [meterscao/Speechless#11]

**Comment by meterscao** [comment]
我已经很久没用过 FF 了，不清楚 FF 插件的具体逻辑，整个插件没有用到特别 Tricky 的 Chrome Api，唯一依赖的是在 保存预览的时候 用到了 Chrome 的另存为 PDF，这也是这个插件成立的关键。

你如果感兴趣的话，非常欢迎一起试试 😊
