### ISSUE TITLE
请问我两次每次都只能保存3996条记录是怎么回事呢？

### ISSUE THREAD

**Issue by code-agree** [meterscao/Speechless#12]
感谢作者，感谢开源提供工具！
请问我两次每次都只能保存3996条记录是怎么回事呢？
期待解答，谢谢！

**Comment by meterscao** [comment]
总共的微博数量是多少呢? 方便的话提供下微博id

**Comment by code-agree** [comment]
谢谢回复！我今天又重新导出了一次，可以完整导出了，前几次应该是有中断，导致没有导出完整的3996条微博。

**Comment by meterscao** [comment]
看起来应该是有某一次请求挂掉了，导致后面的中断，我来保护下

**Comment by meterscao** [comment]
![image](https://user-images.githubusercontent.com/1685497/210031433-e817bde9-c8b1-46cb-84e0-586c09c436cb.png)
2.0版本将支持选择月份进行导出
