### ISSUE TITLE
图片保存不完整

### ISSUE THREAD

**Issue by segfault-bilibili** [meterscao/Speechless#15]
即便在网页上右键打开，也只是分辨率很差的缩略图

**Comment by segfault-bilibili** [comment]
感觉未必非得要虚拟打印成PDF，保存成MHT之类应该也可以？  #17

**Comment by segfault-bilibili** [comment]
https://github.com/meterscao/Speechless/blob/588f8017874cf9f15fe4bb392fc20b036e127644/src/scripts/content.js#L190

只要这里把bmiddle改成original应该就是原图了，但我还没测试。

**Comment by meterscao** [comment]
默认不使用原图的原因是会导致最终生成pdf失败，在另一个分支中已经加入了【原图】的可选项，静待更新

**Comment by segfault-bilibili** [comment]
昨天说实话我基本上是因为要急用才下手改的，要备份一个游戏的官号。另外不知道你对另存为mhtml有何意见，个人觉得这样更完整一些（比如链接）。

**Comment by meterscao** [comment]
目前我仍然认为pdf是更适合大多数人的备份格式，特别是在手机上预览和分享。
