### ISSUE TITLE
请求数量太大，会导致命中微博的IP限制，返回 414 错误码

### ISSUE THREAD

**Issue by meterscao** [meterscao/Speechless#2]
考虑降低请求的频率，避免发生 `414` 错误

**Comment by meterscao** [comment]
内容参考：
- [高并发的场景下，不能不说的限流算法](https://juejin.cn/post/6844904031022743560)
- [最常用的限流算法以及如何在http中间件中加入流控](https://segmentfault.com/a/1190000040127959)

**Comment by meterscao** [comment]
在公司 IP 下进行拉取无论如何都无法命中 IP 限制，只能今晚回去再看看

**Comment by shincling** [comment]
感谢作者。这个问题我也遇到了，2W多条，保存到大概7K左右因为微博的限制停掉了。看到作者在关注这个问题了，期待。

我提一个小的Feature，**能否自选一下保存的范围**？ 比如只保存某个时间节点的。这样的好处是：

- 触发限流了导致中断，可以过后一段时间从断点处继续
- 对于微博较多的话痨（比如俺），可以较好地规避最后的PDF过大的问题

印象中微博的个人主页本身有个具体到月的Button，后台应该有可以过滤时间的API，感觉应该可以从这里入手。

请作者参考~~
再次感谢。

**Comment by meterscao** [comment]
<img width="288" alt="image" src="https://user-images.githubusercontent.com/1685497/204483521-beaab43e-12cd-4232-8d65-97a0a01621d0.png">
我看到了，确实有这么个月历，不知道能不能用起来，试试看先。

**Comment by meterscao** [comment]
@shincling 2.0 版本已经支持 https://speechless.fun

**Comment by shincling** [comment]
> @shincling 2.0 版本已经支持 https://speechless.fun

感谢作者！这么久了，还有后续的feature支持，respect ！
