### ISSUE TITLE
能否下载高清图片

### ISSUE THREAD

**Issue by mdzzdsbhz** [meterscao/Speechless#21]
想看有些博主写的文，但是以图片形式发送的，直接保存会变成这样
![image](https://user-images.githubusercontent.com/62829719/210292649-4b20cca8-f837-41b1-a85c-dfbfc24a3dca.png)

**Comment by meterscao** [comment]
最新开发的版本已经支持原图，请稍等下

**Comment by meterscao** [comment]
@mdzzdsbhz 2.0 版本已经支持了
https://github.com/meterscao/Speechless/pull/24#issue-1686739251
