### ISSUE TITLE
超过五年的无法导出

### ISSUE THREAD

**Issue by kevinluok** [meterscao/Speechless#23]
感谢开发微博导出插件，但现在存在以下问题。
1、超过三年的无法导出，现在只能导到2018年3月。
2、只能微博网页版才能使用插件，而网页版现在只能显示近五年的微博，且无法返回旧版。
3、https://m.weibo.cn/可以显示全部微博，但无法使用插件。
4、是否有办法可以导出https://m.weibo.cn/网页微博？

**Comment by meterscao** [comment]
新版本的插件在开发中，需要晚一些时候才能发布。
关于提到手机版能显示全部微博这个细节，我花时间看看，感谢线索。

**Comment by meterscao** [comment]
我验证了几个，发现手机端和桌面导出的限制同步了，不知道是否是微博做了策略调整

**Comment by meterscao** [comment]
https://github.com/meterscao/Speechless/issues/35#issuecomment-1680016014
