### ISSUE TITLE
[Bug] underline 与下弯钩字母冲突

### ISSUE THREAD

**Issue by jingfelix** [meterscao/Speechless#26]
浏览器版本：macOS Chrome 112.0.5615.137
相关URL：https://weibo.com/flypig
描述：”把@flypig的记忆打包“这行文字的下划线与文字中的下弯钩字母（如y，p，q）等存在显示冲突
其他：尝试给`<label>`元素添加了类`underline-offset-4`，但没有生效。也许这是个feature……？
图片：
<img width="364" alt="截屏2023-05-01 13 59 21" src="https://user-images.githubusercontent.com/72600955/235414832-616d9fde-86cc-4ef0-831f-3a97385a0383.png">

**Comment by meterscao** [comment]
😂，确定不是feature，这个可能是underline渲染的问题

https://stackoverflow.com/questions/49760273/text-decoration-underline-for-dom-element-doesnt-underline-for-all-letters-in-a
