### ISSUE TITLE
能不能保留段落之间的空行？

### ISSUE THREAD

**Issue by smallyunet** [meterscao/Speechless#28]
这是原文：
<img width="625" alt="Screenshot 2023-05-12 at 11 41 28" src="https://github.com/meterscao/Speechless/assets/20765689/fc669b6e-3fd1-4ff9-a1ff-a5c16ba9acd3">

这是保存的内容：
<img width="928" alt="Screenshot 2023-05-12 at 11 42 34" src="https://github.com/meterscao/Speechless/assets/20765689/845c1412-d7f1-4385-b029-a8e3401497f1">

因为去掉了空行，导致可读性变差了

**Comment by meterscao** [comment]
明白，应该是这个正则没有写好的原因，本意是把多余的换行给清理掉，现在看起来应该是把连续超过2个的换行替换成一个

**Comment by meterscao** [comment]
v2.2 会优化

**Comment by meterscao** [comment]
f98d56ee11adeadde4bf61b41df5173cd1126c7e

v2.2

- 修复了长文无法展开，只显示“展开”两个字的问题
- 保留了文本内容内的换行，使内容阅读体验更佳
- 优化了导出文件的标题
