### ISSUE TITLE
希望文件名中的月份固定位数，不足则添加前导 0

### ISSUE THREAD

**Issue by Konano** [meterscao/Speechless#31]
https://github.com/meterscao/Speechless/blob/5a125c03d223b0415413fa1303b207e3bcd2debd/src/App.vue#L399-L402

这里没有对 month 做 fillWithZero，导致文件名长度不一

**Comment by meterscao** [comment]
v2.2 会优化

**Comment by meterscao** [comment]
f98d56ee11adeadde4bf61b41df5173cd1126c7e

v2.2

- 修复了长文无法展开，只显示“展开”两个字的问题
- 保留了文本内容内的换行，使内容阅读体验更佳
- 优化了导出文件的标题
