### ISSUE TITLE
导出过程中可能会因为 API 限制而停止导出，从而导致内容不全

### ISSUE THREAD

**Issue by Konano** [meterscao/Speechless#32]

**Comment by meterscao** [comment]
跟 API 限制无关，微博限制了某些年份之前的微博不能通过 web 网页浏览。暂时还没有好的办法

**Comment by Konano** [comment]
> 跟 API 限制无关，微博限制了某些年份之前的微博不能通过 web 网页浏览。暂时还没有好的办法

我在导出的过程中并没有遇到您描述的问题，已经成功导出 2012 年的微博。我遇到的是别的问题。

简单来说，我在尝试导出微博时指定了三个不同但又重叠的时间段：
- A: 2018.01-2018.03
- B: 2018.04-2018.06
- C: 2018.01-2018.06

这三者的数量正常情况下 A+B=C，但实际情况是 A+B>C。

能否 reopne 该 issue，我找个时间复现一下，看看浏览器 network 调试一下？

**Comment by meterscao** [comment]
好的，如果有复现，请帮忙更新下

**Comment by iftfish** [comment]
我也遇到了同样的问题。

我的微博内容比较多，所以选择了一个月的时间范围来下载，例如：同一年的1月～1月。但是导出的内容只包括1月31日到1月15日，前面的没有了。我在微博web页上手动输入1月1日～1月31日点搜索，往下滑动，的确到1月15日之后就卡住显示不出内容了，和导出的结果是一致的；但是如果重新搜索1月1日～1月14日，前面部分的内容也是可以完整显示出来的。

所以想问下能否把时间范围的输入从“年+月”进一步精确到“年+月+日”，用户检查到导出内容不完整后，可以手动再调整下具体日期把缺少的部分补回来，感谢

**Comment by meterscao** [comment]
目前的实现里面可能不太行，我用的是微博的web端接口。不过我研究研究  ‘如果重新搜索1月1日～1月14日’

**Comment by andashuai1997** [comment]
我也是遇到导出不完整的情况，自己选择时间区间能看到内容，但是直接全部导出不完整，只大概导出了三年的内容

**Comment by meterscao** [comment]
这个项目暂时会归档起来不再继续维护，接下来启用新的项目，如果大家有需要可以 fork 现有的项目。
