### ISSUE TITLE
长微博无法自动展开

### ISSUE THREAD

**Issue by YunQimg** [meterscao/Speechless#33]
速度很快，体验很好。
有个问题麻烦作者解答一下: 在保存几年前的微博时, 部分微博会显示"展开"按钮, 手动点击也不能展开.
![1686747524201](https://github.com/meterscao/Speechless/assets/14855978/ff099915-f4ea-4afc-9b5d-5936b6a66786)

这种情况该如何解决呢?

**Comment by meterscao** [comment]
这个看起来是 bug

**Comment by meterscao** [comment]
f98d56ee11adeadde4bf61b41df5173cd1126c7e

v2.2

- 修复了长文无法展开，只显示“展开”两个字的问题
- 保留了文本内容内的换行，使内容阅读体验更佳
- 优化了导出文件的标题
