### ISSUE TITLE
关于Speechless内容采集情况

### ISSUE THREAD

**Issue by Husky-lee** [meterscao/Speechless#34]
他人微博在m.weibo.cn下能查看所有微博内容，在www.weibo.com里只能采集部分内容，我采集朋友的微博700多条只能拉取126条，所以Speechless可以支持m.weibo.cn的内容采集吗？谢谢。

**Comment by meterscao** [comment]
是的 ，之前也有同学提到这个问题，一直想去尝试，但是一直没时间弄。

**Comment by Husky-lee** [comment]
> 是的 ，之前也有同学提到这个问题，一直想去尝试，但是一直没时间弄。

**Comment by Husky-lee** [comment]
> 是的 ，之前也有同学提到这个问题，一直想去尝试，但是一直没时间弄。

辛苦，好人一生平安。
