### ISSUE TITLE
想请问：未来有加入微博文章的图片爬取功能的打算吗

### ISSUE THREAD

**Issue by lingos33** [meterscao/Speechless#37]
如题，因为现阶段只能进行微博十八图的爬取所以想问问。不过鉴于我也不了解微博的图片机制，所以作者没有这个打算/开发很困难也没关系！总之感谢作者的插件！

**Comment by meterscao** [comment]
暂时还没有这个计划，主要目前是够用了，如果你感兴趣，欢迎fork
