### ISSUE TITLE
图片比例变形问题

### ISSUE THREAD

**Issue by Sansui233** [meterscao/Speechless#38]
目前图片以 height 限制大小，max-width限制100%，导致图片横向长度大于窗口宽度时，图片被横向压缩。

希望改为 max-height 限制高度, 以保持图片比例不变形。

**Comment by meterscao** [comment]
有变形的case么，帮忙截图我看看

**Comment by Sansui233** [comment]
<img width="888" alt="image" src="https://github.com/meterscao/Speechless/assets/27474981/aef25997-9fac-4628-a2c1-61d711d384e4">

好像主要是老一点的图有问题。有些图打印到A4宽度后也会被压。我目前加了Stylus临时处理了下，存了几千条，记不清打印出来有问题的是哪张图了……

**Comment by meterscao** [comment]
可能是很早前的图片没有image的宽高数据，目前排版用了一个很复杂的方法来实现类似于 500px 的效果

**Comment by bitzip** [comment]
在 2012 年（包括） 之前的图片比例有问题，导出时将 CSS 改成 `height: auto !important` 临时解决

**Comment by meterscao** [comment]
@bitzip 好的 感谢 这个版本即将归档 ，新版本在开发当中了
