### ISSUE TITLE
Cannot install it from Google Extension store

### ISSUE THREAD

**Issue by jjhhms** [meterscao/Speechless#4]
Hi, when I tried to install it from google store, it said some of images cannot be loaded. May need check it

**Comment by meterscao** [comment]
你能贴一下截图吗，是 Google Store 里面的预览图不能加载，还是插件里面的图片不能加载，还是微博的图片不能加载？

**Comment by jjhhms** [comment]
FYI
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/108176698/203220723-da51b25e-5e05-4402-97df-b015110872cc.png">

I can still re-pro it on Linux Chrome/Edge

**Comment by meterscao** [comment]
能看下你的Chrome版本吗

`版本 107.0.5304.110（正式版本）`

**Comment by meterscao** [comment]
Oops，我发现了 ，icon image 的名字 大小写没对上，这个在 Linux 上出现了，我修复下

**Comment by meterscao** [comment]
新扩展包已经提交审核，大概需要1、2天时间，可以把代码 Clone 到本地，直接通过 Chrome 的 `chrome://extensions/` 【加载已解压的扩展程序】来使用。

**Comment by jjhhms** [comment]
Thank you for your efforts.

May we all have rights we are born to have.
