### ISSUE TITLE
请问能否增加增量获取功能

### ISSUE THREAD

**Issue by tinymins** [meterscao/Speechless#40]
导出数量巨大的微博记录时，有时候因为网络、机器问题中断；或隔段时间想要增量备份微博记录时，此时不需要再次重复获取之前的记录。

所以是否可以通过将以获取的数据存储到 localStorage 中等方式，跳过已拉取的微博记录，从而加速备份逻辑呢？

感谢！

**Comment by tinymins** [comment]
以及实测，微博搜索接口最多只能输出1000条微博，选全部日期的情况下循环调用接口得不停修改endtime，现在的逻辑每次只能备份部分微博

**Comment by meterscao** [comment]
Local storage 貌似有5M 的限制。
感谢你的建议，新的版本我会想办法解决

**Comment by tinymins** [comment]
> Local storage 貌似有5M 的限制。 感谢你的建议，新的版本我会想办法解决

插件系统限制可以放开的： unlimitedStorage https://developer.chrome.com/docs/extensions/reference/storage/#property-local

**Comment by meterscao** [comment]
新版本工具开发中，会用别的方法来实现增量获取，现有的项目暂时归档不再维护。
