### ISSUE TITLE
如果账号被封会怎样？

### ISSUE THREAD

**Issue by segfault-bilibili** [meterscao/Speechless#7]
之前关注的一些博主分享了很多有价值的内容，但账号被封，不知道博主本人还有没有可能备份导出原账号数据。

**Comment by meterscao** [comment]
我自己就有账号被封禁，账号拥有者自己可以登录进自己的主页，其他人看不到而已，可以正常导出。

Speechless插件初衷就是给这批被封禁账号的人使用的，希望能帮助到你。
